site_name: harborapi
theme:
  name: "material"
plugins:
- search
- autorefs
- mkdocstrings:
    enable_inventory: true
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        options:
          docstring_style: numpy
          members_order: source
          docstring_section_style: table
          show_source: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - index.md
  - "Usage":
    - usage/_intro.md
    - usage/examples.md
    - usage/exceptions.md
    - usage/sync-client.md
  - "Endpoints":
    - endpoints/_overview.md
    - endpoints/artifacts.md
    - endpoints/audit.md
    - endpoints/cveallowlist.md
    - endpoints/health.md
    - endpoints/oidc.md
    - endpoints/ping.md
    - endpoints/projects.md
    - endpoints/quota.md
    - endpoints/registries.md
    - endpoints/repositories.md
    - endpoints/scan.md
    - endpoints/scanall.md
    - endpoints/scanners.md
    - endpoints/search.md
    - endpoints/statistics.md
    - endpoints/systeminfo.md
    - endpoints/users.md
  - "Reference":
    - reference/exceptions.md
    - reference/client.md
  - "Models":
    - models/models.md
